spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://google/studyschedule?cloudSqlInstance=polar-processor-235700:us-central1:studydbms&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: root
    password: J4JO8pJn0bzmbj5m
   
mybatis:
  mapper-locations:
  - classpath:sqlmapper/*.xml

